package com.app.rest6;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.entity1.User;
import com.app.payload2.UserRequest;
import com.app.payload2.UserResponse;
import com.app.service4.IUserService;
import com.app.util8.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private IUserService service;
	
	@Autowired
	private JwtUtil util;
	
	@PostMapping("/save")
	public ResponseEntity<String> saveuser(@RequestBody User user){
		 service.saveUser(user);
		// return new ResponseEntity<String>("user created",HttpStatus.OK);
		return ResponseEntity.ok("User Created");
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest) {
		
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						userRequest.getUsername(), 
						userRequest.getPassword()
						)
				);
		String token = util.generateToken(userRequest.getUsername());
		
		return ResponseEntity.ok(new UserResponse(token, "Generated By Mr.PRAVEEN"));
	}
	
	
	@PostMapping("/welcome")
	public ResponseEntity<String> showUserData(Principal p) {
		System.out.println(p.getClass().getName());
		return ResponseEntity.ok("Hello :" + p.getName());
	}
	
	

}
